[package]
name = "xgboost_runtime_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xgboost = "0.1.4"
ndarray = "0.15.6"
rand = "0.8.5"